//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public long GoodsId { get; set; }
        public string Card { get; set; }
        public decimal Money { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual User User { get; set; }
    }
}
